[versions]
compose = "1.3.0-beta01"
compose_m3 = "1.0.0-beta01"
compose_compiler = "1.3.0"
accompanist = "0.26.1-alpha"
hilt = "2.43.2"
retrofit = "2.9.0"
richText = "0.13.0"
protobuf = "3.21.5"
wire = "4.4.1"

[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
moshix = { id = "dev.zacsweers.moshix", version = "0.18.3" }
protobuf = { id = "com.google.protobuf", version = "0.8.19" }
wire = { id = "com.squareup.wire", version.ref = "wire" }

[libraries]
androidCoreKtx = "androidx.core:core-ktx:1.8.0"
androidPalette = "androidx.palette:palette-ktx:1.0.0"
androidLifecycleKtx = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"
androidCustomView = "androidx.customview:customview:1.2.0-alpha01"
androidCustomViewPoolingContainer = "androidx.customview:customview-poolingcontainer:1.0.0"

kotlinDatetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"

composeMaterial = { module = "androidx.compose.material:material", version.ref = "compose" }
composeMaterialIcons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
composeMaterial3 = { module = "androidx.compose.material3:material3", version.ref = "compose_m3" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
composeUiUtil = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
composeTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
composeNavigation = "androidx.navigation:navigation-compose:2.5.1"
composeActivity = "androidx.activity:activity-compose:1.5.1"

accompanistNavigation = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanistSystemUi = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanistPager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanistPagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }

coilCompose = "io.coil-kt:coil-compose:2.2.0"
coilGif = "io.coil-kt:coil-gif:2.2.0"
mmkv = "com.tencent:mmkv:1.2.14"

hiltNavigation = "androidx.hilt:hilt-navigation-compose:1.0.0"
hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitMoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofitProtobuf = { module = "com.squareup.retrofit2:converter-protobuf", version.ref = "retrofit" }

richTextMaterial3 = { module = "com.halilibo.compose-richtext:richtext-ui-material3", version.ref = "richText" }
richTextMarkdown = { module = "com.halilibo.compose-richtext:richtext-commonmark", version.ref = "richText" }

wireRuntime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }

javaInject = "javax.inject:javax.inject:1"

okhttp = "com.squareup.okhttp3:okhttp:4.10.0"
bouncyCastle = "org.bouncycastle:bcprov-jdk15to18:1.71"

protobufRuntime = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }

[bundles]
androidx = ["androidCoreKtx", "androidPalette", "androidLifecycleKtx", "androidCustomView", "androidCustomViewPoolingContainer"]
compose = ["composeMaterial", "composeMaterialIcons", "composeMaterial3", "composeUi", "composeUiUtil", "composeNavigation", "composeActivity"]
composeDebug = ["composeUiTooling", "composeUiToolingPreview", "composeTestManifest"]
hilt = ["hiltNavigation", "hiltAndroid", "hiltCompiler"]
accompanist = ["accompanistNavigation", "accompanistSystemUi", "accompanistPager", "accompanistPagerIndicators"]
retrofit = ["retrofit", "retrofitMoshi"]
richText = ["richTextMaterial3", "richTextMarkdown"]